esphome:
  platformio_options:
    upload_speed: 921600

esp32:
  board: lilygo-t3-s3
  flash_size: 4MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf

logger:
  level: debug
  baud_rate: 115200

spi:
  clk_pin:
    number: GPIO05
    ignore_strapping_warning: true
  mosi_pin: GPIO06
  miso_pin: GPIO03

i2c:
  frequency: 800kHz
  scan: False
  sda: GPIO18
  scl:
    number: GPIO17
    ignore_strapping_warning: true

display:
  - platform: ssd1306_i2c
    model: SSD1306 128x64
    address: 0x3C
    auto_clear_enabled: True
    contrast: 50%
    reset_pin:
      number: GPIO08
    update_interval: never

output:
  - platform: gpio
    id: vext_output
    pin: GPIO43
    inverted: True

light:
  - platform: status_led
    id: wmbus_gateway_status_led
    pin: GPIO37

binary_sensor:
  - platform: gpio
    id: ext_button
    pin:
      number: GPIO00
      ignore_strapping_warning: true
      mode: input
      inverted: True
