packages:
  hal: !include
    file: lilygo_t3_s3.yaml
  resources: !include
    file: resources.yaml
  version: !include
    file: version.yaml

external_components:
  - source: 
      type: git
      url: https://github.com/papuga2000/ESPHome-Components
      ref: ${esphome_components_version}
    components:
      - wmbus_common
      - wmbus_radio
      - wmbus_meter
  - source: 
      type: git
      url: https://github.com/papuga2000/wM-Bus-Gateway
      ref: ${wmbus_gateway_version}
    components:
      - wmbus_gateway

esphome:
  name: wmbus-gateway
  friendly_name: wM-Bus Gateway
  comment: wM-Bus Gateway for ESPHome
  project:
    name: IoTLabs.wM-Bus Gateway
    version: ${wmbus_gateway_version}

wmbus_radio:
  radio_type: SX1276
  cs_pin: GPIO7
  reset_pin: GPIO8
  irq_pin: GPIO33
  on_frame:
    - then:
        - repeat:
            count: 20
            then:
              - light.control:
                  id: wmbus_gateway_status_led
                  state: !lambda return iteration % 2 == 0;
              - delay: 50ms

wmbus_gateway:
